---
# handlers file for prometheus
- name: restart prometheus
  service: 
    name: prometheus 
    state: restarted
    daemon_reload: yes
    enabled: yes  

- name: restart node_exporter
  service: 
    name: node_exporter 
    state: restarted
    daemon_reload: yes
    enabled: yes 