# tasks file for prometheus
- name: Create installation folder in etc
  file:
    path: "{{ prometheus_dest_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    recurse: yes

- name: Create data folder
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"     
    mode: '0775'
    recurse: yes

- name: Download/unarchive Packages for prometheus
  unarchive:
    src: "{{ prometheus_download_url }}"
    dest: /root
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}" 
    remote_src: yes
    creates: "{{ prometheus_download_dir }}"


- name: Copying the service binaries for Prometheus
  copy:
    src: "{{ prometheus_download_dir }}/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: '0775'
    remote_src: yes
  loop:
    - prometheus
    - promtool
     
- name: Copying the console binary
  copy:
    src: "{{ prometheus_download_dir }}/{{ item }}"
    dest: "{{ prometheus_dest_dir }}"
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}"    
    mode: '0775'
    remote_src: yes
  loop:
   - consoles
   - console_libraries 

- name: Removing the tar file of prometheus
  file:
    path: "{{ prometheus_download_dir }}"
    state: absent

- name: Create prometheus systemd service file
  template:
    src: templates/prometheus.service.j2
    dest: "{{ service_dest_dir }}/prometheus.service"   

- name: Download/unarchive Packages for node_exporter
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /root
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    remote_src: yes
    creates: "{{ node_exporter_download_dir }}"

- name: Copying the service binary for node_exporter
  copy:
    src: "{{ node_exporter_download_dir }}/{{ item }}"
    dest: /usr/local/bin/
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"   
    mode: '0775'
    remote_src: yes
  loop:
   - node_exporter    

- name: Removing the tar file of node_exporter
  file:
    path: "{{ node_exporter_download_dir }}"
    state: absent

- name: Create node_exporter systemd service file
  template:
    src: templates/node_exporter.service.j2
    dest: "{{ service_dest_dir }}/node_exporter.service"

- name: Copying the scrape config
  template:  
    src: templates/prometheus.yml.j2
    dest: "{{ prometheus_dest_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}" 
    group: "{{ prometheus_user }}" 
    mode: '0775'
  notify:
  - restart prometheus 
  - restart node_exporter